In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
data = pd.read_csv('Loan_default.csv')
data.head()

LoanID  Age  Income  LoanAmount  CreditScore  MonthsEmployed  \
0  I38PQUQS96   56   85994       50587          520              80   
1  HPSK72WA7R   69   50432      124440          458              15   
2  C1OZ6DPJ8Y   46   84208      129188          451              26   
3  V2KKSFM3UN   32   31713       44799          743               0   
4  EY08JDHTZP   60   20437        9139          633               8   

   NumCreditLines  InterestRate  LoanTerm  DTIRatio    Education  \
0               4         15.23        36      0.44   Bachelor's   
1               1          4.81        60      0.68     Master's   
2               3         21.17        24      0.31     Master's   
3               3          7.07        24      0.23  High School   
4               4          6.51        48      0.73   Bachelor's   

  EmploymentType MaritalStatus HasMortgage HasDependents LoanPurpose  \
0      Full-time      Divorced         Yes           Yes       Other   
1      Full-time       Married          No            No       Other   
2     Unemployed      Divorced         Yes           Yes        Auto   
3      Full-time       Married          No            No    Business   
4     Unemployed      Divorced          No           Yes        Auto   

  HasCoSigner  Default  
0         Yes        0  
1         Yes        0  
2          No        1  
3          No        0  
4          No        0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 18 columns):
 #   Column          Non-Null Count   Dtype  
---  ------          --------------   -----  
 0   LoanID          255347 non-null  object 
 1   Age             255347 non-null  int64  
 2   Income          255347 non-null  int64  
 3   LoanAmount      255347 non-null  int64  
 4   CreditScore     255347 non-null  int64  
 5   MonthsEmployed  255347 non-null  int64  
 6   NumCreditLines  255347 non-null  int64  
 7   InterestRate    255347 non-null  float64
 8   LoanTerm        255347 non-null  int64  
 9   DTIRatio        255347 non-null  float64
 10  Education       255347 non-null  object 
 11  EmploymentType  255347 non-null  object 
 12  MaritalStatus   255347 non-null  object 
 13  HasMortgage     255347 non-null  object 
 14  HasDependents   255347 non-null  object 
 15  LoanPurpose     255347 non-null  object 
 16  HasCoSigner     255347 non-null  object 
 17  Default   

In [34]:
data.isna().sum()

Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
dtype: int64

In [33]:
cat = data.select_dtypes(include='object').columns
cat

Index(['Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage',
       'HasDependents', 'LoanPurpose', 'HasCoSigner'],
      dtype='object')

In [6]:
data['Education'].unique()

array(["Bachelor's", "Master's", 'High School', 'PhD'], dtype=object)

In [7]:
data.drop('LoanID',axis=1,inplace=True)
data

Age  Income  LoanAmount  CreditScore  MonthsEmployed  NumCreditLines  \
0        56   85994       50587          520              80               4   
1        69   50432      124440          458              15               1   
2        46   84208      129188          451              26               3   
3        32   31713       44799          743               0               3   
4        60   20437        9139          633               8               4   
...     ...     ...         ...          ...             ...             ...   
255342   19   37979      210682          541             109               4   
255343   32   51953      189899          511              14               2   
255344   56   84820      208294          597              70               3   
255345   42   85109       60575          809              40               1   
255346   62   22418       18481          636             113               2   

        InterestRate  LoanTerm  DTIRatio    Education EmploymentType  \
0              15.23        36      0.44   Bachelor's      Full-time   
1               4.81        60      0.68     Master's      Full-time   
2              21.17        24      0.31     Master's     Unemployed   
3               7.07        24      0.23  High School      Full-time   
4               6.51        48      0.73   Bachelor's     Unemployed   
...              ...       ...       ...          ...            ...   
255342         14.11        12      0.85   Bachelor's      Full-time   
255343         11.55        24      0.21  High School      Part-time   
255344          5.29        60      0.50  High School  Self-employed   
255345         20.90        48      0.44  High School      Part-time   
255346          6.73        12      0.48   Bachelor's     Unemployed   

       MaritalStatus HasMortgage HasDependents LoanPurpose HasCoSigner  \
0           Divorced         Yes           Yes       Other         Yes   
1            Married          No            No       Other         Yes   
2           Divorced         Yes           Yes        Auto          No   
3            Married          No            No    Business          No   
4           Divorced          No           Yes        Auto          No   
...              ...         ...           ...         ...         ...   
255342       Married          No            No       Other          No   
255343      Divorced          No            No        Home          No   
255344       Married         Yes           Yes        Auto         Yes   
255345        Single         Yes           Yes       Other          No   
255346      Divorced         Yes            No   Education         Yes   

        Default  
0             0  
1             0  
2             1  
3             0  
4             0  
...         ...  
255342        0  
255343        1  
255344        0  
255345        0  
255346        0  

[255347 rows x 17 columns]

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le = LabelEncoder()

In [35]:
for i in cat:
    data[i] = le.fit_transform(data[i])

In [36]:
data

Age  Income  LoanAmount  CreditScore  MonthsEmployed  NumCreditLines  \
0        56   85994       50587          520              80               4   
1        69   50432      124440          458              15               1   
2        46   84208      129188          451              26               3   
3        32   31713       44799          743               0               3   
4        60   20437        9139          633               8               4   
...     ...     ...         ...          ...             ...             ...   
255342   19   37979      210682          541             109               4   
255343   32   51953      189899          511              14               2   
255344   56   84820      208294          597              70               3   
255345   42   85109       60575          809              40               1   
255346   62   22418       18481          636             113               2   

        InterestRate  LoanTerm  DTIRatio  Education  EmploymentType  \
0              15.23        36      0.44          0               0   
1               4.81        60      0.68          2               0   
2              21.17        24      0.31          2               3   
3               7.07        24      0.23          1               0   
4               6.51        48      0.73          0               3   
...              ...       ...       ...        ...             ...   
255342         14.11        12      0.85          0               0   
255343         11.55        24      0.21          1               1   
255344          5.29        60      0.50          1               2   
255345         20.90        48      0.44          1               1   
255346          6.73        12      0.48          0               3   

        MaritalStatus  HasMortgage  HasDependents  LoanPurpose  HasCoSigner  \
0                   0            1              1            4            1   
1                   1            0              0            4            1   
2                   0            1              1            0            0   
3                   1            0              0            1            0   
4                   0            0              1            0            0   
...               ...          ...            ...          ...          ...   
255342              1            0              0            4            0   
255343              0            0              0            3            0   
255344              1            1              1            0            1   
255345              2            1              1            4            0   
255346              0            1              0            2            1   

        Default  
0             0  
1             0  
2             1  
3             0  
4             0  
...         ...  
255342        0  
255343        1  
255344        0  
255345        0  
255346        0  

[255347 rows x 17 columns]

In [37]:
data.dtypes

Age                 int64
Income              int64
LoanAmount          int64
CreditScore         int64
MonthsEmployed      int64
NumCreditLines      int64
InterestRate      float64
LoanTerm            int64
DTIRatio          float64
Education           int32
EmploymentType      int32
MaritalStatus       int32
HasMortgage         int32
HasDependents       int32
LoanPurpose         int32
HasCoSigner         int32
Default             int64
dtype: object

In [62]:
X_c = data.drop('Default',axis=1)
y_c = data[['Default']]

In [63]:
X_r = data.drop('LoanAmount',axis=1)
y_r = data[['LoanAmount']]

In [64]:
from sklearn.model_selection import train_test_split

In [65]:
c_X_train,c_X_test,c_y_train,c_y_test = train_test_split(X_c,y_c,test_size=0.2)

In [66]:
from sklearn.tree import DecisionTreeClassifier

In [67]:
DTC = DecisionTreeClassifier()

In [68]:
DTC.fit(c_X_train,c_y_train)

DecisionTreeClassifier()

In [69]:
c_y_pred = DTC.predict(c_X_test)

In [70]:
c_y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [71]:
from sklearn.metrics import accuracy_score

In [72]:
accuracy_score = (c_y_test,c_y_pred)

In [73]:
accuracy_score

(        Default
 183270        0
 198836        0
 185995        1
 10430         0
 58595         0
 ...         ...
 117289        0
 15082         0
 68601         0
 58257         0
 64380         0
 
 [51070 rows x 1 columns],
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64))

In [74]:
r_X_train,r_X_test,r_y_train,r_y_test = train_test_split(X_r,y_r,test_size=0.2)

In [75]:
from sklearn.tree import DecisionTreeRegressor

In [76]:
DTC = DecisionTreeRegressor()

In [77]:
DTC.fit(r_X_train,r_y_train)

DecisionTreeRegressor()

In [78]:
r_y_pred = DTC.predict(r_X_test)

In [79]:
r_y_pred

array([ 85145.,  64177., 119546., ...,  17915., 147305., 152977.])

In [80]:
from sklearn.metrics import r2_score

In [81]:
r2_score = (r_y_test,r_y_pred)

In [82]:
r2_score

(        LoanAmount
 212804      240345
 99018        35958
 238770       66413
 73633       228042
 110068      221754
 ...            ...
 11521        20606
 241903       18741
 206412       99935
 250856       77748
 193151       82763
 
 [51070 rows x 1 columns],
 array([ 85145.,  64177., 119546., ...,  17915., 147305., 152977.]))

In [83]:
a = pd.DataFrame(r_y_pred)

In [84]:
pd.concat([r_y_test[:10],a[:10]],axis=1)

LoanAmount         0
212804    240345.0       NaN
99018      35958.0       NaN
238770     66413.0       NaN
73633     228042.0       NaN
110068    221754.0       NaN
202855    231020.0       NaN
160867    170608.0       NaN
231941     83410.0       NaN
135943     18942.0       NaN
69109     171973.0       NaN
0              NaN   85145.0
1              NaN   64177.0
2              NaN  119546.0
3              NaN  128565.0
4              NaN  202126.0
5              NaN  223277.0
6              NaN   94122.0
7              NaN   48255.0
8              NaN    8144.0
9              NaN   79441.0

In [ ]:
plt.plot(data['Income'],data['LoanAmount'])
plt.show()

In [31]:
data['LoanAmount'].mean()

127578.86551242035